#!/usr/bin/env python

import sys
import zmq

PORT = 15556

if len(sys.argv) < 2:
    print "Usage: %s <txid>" % sys.argv[0]
    sys.exit(1)

context = zmq.Context()
socket = context.socket(zmq.REQ)
socket.connect("tcp://127.0.0.1:%s" % PORT)

socket.send(sys.argv[1])
socket.recv()   # for completeness' sake
